### ISSUE TITLE
License of project?

### ISSUE THREAD

**Issue by lilumdaru** [rsodre/FulldomeCameraForUnity#12]
Hi,

thanks for your great camera asset. 

It came to my notice, that you didn't choose a license for your project, yet. What license are you planning to use? 

Unfortunally without knowing the license I can't use this in my project :/ (company regulations)

**Comment by rsodre** [comment]
Hey!
MIT is good.
It is available as-is to do anything you want with it!
I'll add a LICENCE file to the project.
