### ISSUE TITLE
DXR/Ray Tracing support?

### ISSUE THREAD

**Issue by ahfontaine** [rsodre/FulldomeCameraForUnity#5]
More of a suggestion : as I was reading the description, this part popped up in my head : "would use our custom method that calculate rays from the camera to world, for each pixel."
Is DXR/Experimental HDRP/Ray Tracing any good for solving this issue?

**Comment by rsodre** [comment]
I hope so! There's a sligthly complicated RT tutorial, and I haven't seen the API yet.
Since DXR is a NVidia/PC thin, I don't think I'll be touching it any time soon.

**Comment by ahfontaine** [comment]
Oh great! I read that Unity will implement Vulkan RT support after they're done with DXR.

**Comment by rsodre** [comment]
Closing this since I have no intention to try it anytime soon.
