### ISSUE TITLE
Question about HDRP

### ISSUE THREAD

**Issue by mrarashiyan** [rsodre/FulldomeCameraForUnity#6]
Hi,
Thank you for this useful package
a have a question:
can I use this package with HDRP or LDRP?

**Comment by rsodre** [comment]
Yes, the master branch is compatible with HDRP.
I haven't tried LWRP but should work too. Please tell what happens here if you try.

**Comment by mrarashiyan** [comment]
Hi there,
yup it's working. I used 2019 version on Unity 2018.3.7 .
Just had a little change in FullDomeCamera.cs  on line 102. I'd commented "if" statement in order to force it to use "cubemapFbo" as main renderer texture
Thank you
