### ISSUE TITLE
Script Class cannot be found

### ISSUE THREAD

**Issue by SantoorSingh** [rsodre/FulldomeCameraForUnity#8]
Hi,

I'm using Unity 2019.2.14f1 and I am a complete beginner. I'm trying to follow the instructions on how to use the FullDomeCamera. I have created an empty GameObject but when I try to add the FulldomeForUnity/FulldomeCamera/Scripts/FulldomeCamera.cs script to it, I get a pop up saying that the script class cannot be found and that I need to check whether there are any compile errors. I had a look at the standard example scene provided in the file, but that's not working either. 

Could you let me know what I'm doing wrong?

Thankyou

Eeshar

**Comment by rsodre** [comment]
Hi! Did you check if there's any error in the console?

**Comment by rsodre** [comment]
Closing for innactivity. Please try the current master branch,
